// <auto-generated />
namespace TechnicalInterview_FeedReader.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class AddStoryExternalId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStoryExternalId));
        
        string IMigrationMetadata.Id
        {
            get { return "201312070419395_Add Story External Id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
